version: '3'
services:
  vue:
    build:
      context: ./docker/vue
    command: sh -c "yarn install && yarn serve"
    container_name: chat-vue
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./client:/app
    working_dir: /app

  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: fresh
    container_name: chat-go
    ports:
      - 8082:8082
    tty: true
    volumes:
      - .:/go/src
    working_dir: /go/src/server
