FROM golang:1.18 as builder

RUN apt-get update

WORKDIR /go/src/server

COPY ./server /go/src/server

# Linux用にコンパイルするための環境変数
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN go build main.go

FROM alpine:latest

COPY --from=builder /go/src/server /app

RUN apk add go && \
  go get bitbucket.org/liamstask/goose/cmd/goose@latest

ENV PATH "/root/go/bin:$PATH"

CMD /app/main $PORT
